### PR TITLE
Hash dialogue ids instead of randomizing

### PR DESCRIPTION
**Pull request by adampauls**
This makes the process of producing the leaderboard reproducible but still non-invertible.

### CODE REVIEW

**Review by sroy9 — APPROVED** [review]
Looks good. Thanks !

**Review by sammthomson — APPROVED** [review]
This looks great, thanks! cc @hao-fang re `make format`

**Comment by hao-fang** [comment]
Fixed -- the issue is unused import
```
************* Module dataflow.leaderboard.create_leaderboard_data
src/dataflow/leaderboard/create_leaderboard_data.py:11:0: W0611: Unused import string (unused-import)
```

**Comment by hao-fang** [comment]
.. and fixed mypy error with this commit https://github.com/microsoft/task_oriented_dialogue_as_dataflow_synthesis/pull/22/commits/23a1e77e447fb833ab08ca60f6cdaeb794ff2813

**Comment by adampauls** [comment]
Thanks for cleaning up the lint errors @hao-fang!

**Pull request merged**
